definitions:
  wallet.Err:
    properties:
      message:
        type: string
    type: object
  wallet.Wallet:
    properties:
      balance:
        example: 100
        type: number
      created_at:
        example: "2024-03-25T14:19:00.729237Z"
        type: string
      id:
        example: 1
        type: integer
      user_id:
        example: 1
        type: integer
      user_name:
        example: John Doe
        type: string
      wallet_name:
        example: John's Wallet
        type: string
      wallet_type:
        example: Credit Card
        type: string
    type: object
  wallet.WalletPayload:
    properties:
      balance:
        example: 100
        type: number
      user_id:
        example: 1
        type: integer
      user_name:
        example: John Doe
        type: string
      wallet_name:
        example: John's Wallet
        type: string
      wallet_type:
        example: Credit Card
        type: string
    required:
    - balance
    - user_id
    - user_name
    - wallet_name
    - wallet_type
    type: object
host: localhost:1323
info:
  contact: {}
  description: Sophisticated Wallet API
  title: Wallet API
  version: "1.0"
paths:
  /api/v1/wallets:
    get:
      consumes:
      - application/json
      description: Get all wallets and filter by wallet type
      parameters:
      - description: Filter by wallet type
        enum:
        - Savings
        - Credit Card
        - Crypto Wallet
        in: query
        name: wallet_type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/wallet.Wallet'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wallet.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wallet.Err'
      summary: Get all wallets and filter by wallet type
      tags:
      - wallet
    post:
      consumes:
      - application/json
      description: Create wallet
      parameters:
      - description: Wallet Payload
        format: WalletPayload
        in: body
        name: wallet
        required: true
        schema:
          $ref: '#/definitions/wallet.WalletPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wallet.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wallet.Err'
      summary: Create wallet
      tags:
      - wallet
  /api/v1/wallets/{walletId}:
    get:
      consumes:
      - application/json
      description: Get wallet by id
      parameters:
      - description: Wallet Id
        format: uint64
        in: path
        name: walletId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/wallet.Wallet'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wallet.Err'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/wallet.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wallet.Err'
      summary: Get wallet by id
      tags:
      - wallet
    put:
      consumes:
      - application/json
      description: Update wallet
      parameters:
      - description: Wallet Id
        format: uint64
        in: path
        name: walletId
        type: string
      - description: Wallet Payload
        format: WalletPayload
        in: body
        name: wallet
        required: true
        schema:
          $ref: '#/definitions/wallet.WalletPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wallet.Err'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/wallet.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wallet.Err'
      summary: Update wallet
      tags:
      - wallet
swagger: "2.0"
