definitions:
  ErrorResponse:
    properties:
      result: {}
      status:
        type: string
    type: object
  SuccessResponse:
    properties:
      result: {}
      status:
        type: string
    type: object
  WalletPayload:
    properties:
      balance:
        example: 100
        type: number
      user_id:
        example: 1
        type: integer
      user_name:
        example: John Doe
        type: string
      wallet_name:
        example: John's Wallet
        type: string
      wallet_type:
        example: Credit Card
        type: string
    required:
    - balance
    - user_id
    - user_name
    - wallet_name
    - wallet_type
    type: object
host: localhost:1323
info:
  contact: {}
  description: Sophisticated Wallet API
  title: Wallet API
  version: "1.0"
paths:
  /api/v1/wallets:
    get:
      consumes:
      - application/json
      description: Get all wallets and filter by wallet type
      parameters:
      - description: Filter by wallet type
        enum:
        - Savings
        - Credit Card
        - Crypto Wallet
        in: query
        name: wallet_type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Get all wallets and filter by wallet type
      tags:
      - wallet
    post:
      consumes:
      - application/json
      description: Create wallet
      parameters:
      - description: Wallet Payload
        format: WalletPayload
        in: body
        name: wallet
        required: true
        schema:
          $ref: '#/definitions/WalletPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Create wallet
      tags:
      - wallet
  /api/v1/wallets/{walletId}:
    delete:
      consumes:
      - application/json
      description: Delete wallet by walletId
      parameters:
      - description: Wallet Id
        format: uint64
        in: path
        name: walletId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Delete wallet
      tags:
      - wallet
    get:
      consumes:
      - application/json
      description: Get wallet by walletId
      parameters:
      - description: Wallet Id
        format: uint64
        in: path
        name: walletId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Get wallet
      tags:
      - wallet
    put:
      consumes:
      - application/json
      description: Update wallet by walletId
      parameters:
      - description: Wallet Id
        format: uint64
        in: path
        name: walletId
        required: true
        type: string
      - description: Wallet Payload
        format: WalletPayload
        in: body
        name: wallet
        required: true
        schema:
          $ref: '#/definitions/WalletPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Update wallet
      tags:
      - wallet
swagger: "2.0"
